const ajax = require('./ajax')

//开发环境下需要开启本地后端服务，生产环境需要替换api地址,测试地址不适用于
export const orderForm = (data) => ajax('http://localhost:3000/orderForm', data, 'post')
export const userSpace = (data) => ajax('http://localhost:3000/userspace', data, 'post')
export const sendCheckCode = (data) => ajax('http://localhost:3000/sendcheckcode', data, 'post')
export const verifyCode = (data) => ajax('http://localhost:3000/verifycode', data, 'post')
export const login = (data) => ajax('http://localhost:3000/login', data, 'post')
export const convert = (data) => ajax('http://localhost:3000/pointsmall', data, 'post')
export const joinmember = (data) => ajax('http://localhost:3000/joinmember', data, 'post')
export const discount = (data) => ajax('http://localhost:3000/discount', data, 'post')
export const setPwd = (data) => ajax('http://localhost:3000/setpassword', data, 'post')
export const qrCode = (data) => ajax('http://localhost:3000/qrcode', data, 'post')
export const pointsDetails = (data) => ajax('http://localhost:3000/pointsdetails', data, 'post')
export const record = (data) => ajax('http://localhost:3000/record', data, 'post')
export const expensesRecord = (data) => ajax('http://localhost:3000/expensesrecord', data, 'post')
export const changeCode = (data) => ajax('http://localhost:3000/changecode', data, 'post')
